---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelinesascode-tekton-dev-appstudio-redhat-com-v1alpha1-repository
  failurePolicy: Fail
  name: vrepository.kb.io
  rules:
  - apiGroups:
    - pipelinesascode.tekton.dev.appstudio.redhat.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
